### ISSUE TITLE
improve docs 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [siputra12/fakecall#4]

**Comment by saidako38** [comment]
مين انت

في الخميس، ١٧ سبتمبر ٢٠٢٠ ٧:٣٢ م Tarek Ali <notifications@github.com> كتب:

**Comment by DGKSK8LIFE** [comment]
@saidako38 English please

**Comment by ValentinNikolaev** [comment]
@DGKSK8LIFE check https://github.com/ValentinNikolaev/fakecall

**Comment by DGKSK8LIFE** [comment]
thanks
